specVersion: 0.2.0
name: xcmDemo
version: 0.0.4
description: This SubQuery project can be use as a starting point for Moonriver network
repository: https://github.com/stwiname/subql-xcm-demo
schema:
  file: ./schema.graphql
network:
  endpoint: wss://moonriver.api.onfinality.io/public-ws
  genesisHash: '0x401a1f9dca3da46f5c4091016c8a2f26dcea05865116b286f60f668207d1474b'
  # dictionary: https://api.subquery.network/sq/subquery/moonriver-dictionary
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1652961
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: xTokens
            method: Transferred
        # - handler: handleCall
        #   kind: substrate/CallHandler
